### ISSUE TITLE
Javascript inheritance?

### ISSUE THREAD

**Issue by raq929** [ga-wdi-boston/ruby-objects-composition#10]
There is a section title 'Javascript Inheritance', but there is no text. What does it mean?
Relatedly, what does 'There's a better way' mean in relation to Ruby? 
In short, WAT 0_o

**Comment by jrhorn424** [comment]
This is intended as a place to review the prototype lookup chain to support understanding the method lookup chain in ruby. It's probably better suited as a part of `ruby-object-inheritance`. @gaand do you disagree with that conclusion, or have a different recollection of context?

**Comment by raq929** [comment]
Per our conversation, I have taken the "JavaScript Inheritance' section out this out of the lesson.

**Comment by raq929** [comment]
(In PR #12)
