### ISSUE TITLE
Inheritance/composition/mixins

### ISSUE THREAD

**Issue by raq929** [ga-wdi-boston/ruby-objects-composition#11]
It seems like this repo calls composition what I would call inheritance - see the car example. A ford *is a* car. So, inheritance.

That seems like inheritance to me, whereas what I would call composition is the *has a* relationship - a parent *has a* child.  It uses *classes* for both, as in the example below. (Which would be better as a mixin, but I needed a quick example.)
```Ruby
class Code
    def initialize(person)
        @person = person
    end
    
    def make_bugs
        "#{@person.name} does some typing"
    end
end

class Developer < Employee
    def make_bugs
        Code.new(self).make_bugs
    end 
end
```

Then, my understanding of mixins is as we've described them, they are modules to share *behavior*. 

Am I missing something? If not, I'd like to change the names, and maybe actually discuss composition?

**Comment by jrhorn424** [comment]
Notes from our meeting with @gaand:
-   "inheritance" `is_a` something
-   "composition" `has_[a|many]` something(s)
-   "mixins" `behave_as` something

**Comment by jrhorn424** [comment]
I believe this is in-scope and adequately covered by current material, and therefore closeable.
