### ISSUE TITLE
Loosing square example?

### ISSUE THREAD

**Issue by payne-chris-r** [ga-wdi-boston/ruby-objects-composition#14]
Was there pedagogical purpose for reusing the `square` example? It is now `equine`.

**Comment by raq929** [comment]
I think we decided that squares were a good example for inheritance, but we needed something different for mixins?

**Comment by raq929** [comment]
Ah. This is referenced in PR #12

**Comment by jrhorn424** [comment]
@raq929 since you're fresh on the material, can you please confirm that the shapes lab is present in the inheritance talk? If so, this may be closed.

**Comment by raq929** [comment]
The shapes lab is present in the inheritance talk. With tests!
