### ISSUE TITLE
Naming convention and a common point of confusion: Inheritance versus Mixins

### ISSUE THREAD

**Issue by jrhorn424** [ga-wdi-boston/ruby-objects-composition#9]
If something **is** a something else, use inheritance. If something **behaves** like a something else, use mixins.

A good solution for this is to have all mixins end in **-able**: `Enumerable`, `Comparable`, `Sleepable` (in this README). They represents concerns or sets of behaviors.

**Comment by gaand** [comment]
Should composition, `has-a`, be mentioned along with those?

**Comment by raq929** [comment]
Farther discussion is in #11

**Comment by raq929** [comment]
@jrhorn424 and @gaand Can you take a look at the new material and see if this has been fully addressed? I did a fair amount of work on this for the last update, but I wanted other eyes on it before closing.

**Comment by jrhorn424** [comment]
I believe this is adequately covered given the amount of data we have on delivery. If you feel like it needs to be expanded after delivery this time, feel free to re-open or open a new issue as appropriate. Thanks! @raq929
